var places = [
{
  'name': 'Hubsy',
  'address': '41 Rue Réaumur, 75003 Paris'
  'charge': '5 € /first hour then 2 € / every half-an-hour, 20 € /day',
  'lat': '48.8657378',
  'lon': '2.3541439',
  'url': 'http://www.hubsy.fr',
  'type': 'Co-working café',
  'info': [{'meeting_rooms': 'Yes for 6 persons',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
{
  'name': 'Nuage Café',
  'address': '14 Rue des Carmes, 75005 Paris',
  'charge': '4 €/hour, 16 €/day',
  'lat': '48.8492626',
  'lon': '2.3473711',
  'url': 'https://nuagecafe.fr',
  'type': 'Co-working café',
  'info': [{'meeting_rooms': 'No, but possibility to privatize the space for a meeting.',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
{
  'name': 'Anticafé Louvre',
  'address': '10 Rue de Richelieu, 75001 Paris',
  'charge': '5 €/hour, 24 €/day',
  'lat': '48.8641804',
  'lon': '2.3362479',
  'url': 'http://www.anticafe.eu/louvre/',
  'type': 'Co-working café',
  'info': [{'meeting_rooms': 'For more than four persons possibility to reserve a table or part of Anticafé any time except between 1pm and 6pm.',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
{
  'name': 'Anticafé Beaubourg',
  'address': '79 Rue Quincampoix, 75003 Paris',
  'charge': '5 €/hour, 24 €/day',
  'lat': '48.862592',
  'lon': '2.3512',
  'url': 'http://www.anticafe.eu/beaubourg/',
  'type': 'Co-working café',
  'info': [{'meeting_rooms': 'For 4-15 persons possibility to reserve a table or part of Anticafé any time except between 1pm and 6pm.',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
{
  'name': 'Le 10h10 Coworking Café',
  'address': '19 Rue de Cléry, 75002 Paris',
  'charge': '4.5 €/hour, 20 €/day',
  'lat': '8.8680272',
  'lon': '2.3459806',
  'url': 'http://www.le10h10.com/fr/coworking-cafe/',
  'type': 'Co-working café',
  'info': [{'meeting_rooms': 'Yes, three options. From 6 to 50 persons',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
{
  'name': 'NUMA Cowork',
  'address': '39 Rue du Caire, 75002 Paris',
  'charge': 'free',
  'lat': '48.8676305',
  'lon': '2.3495396',
  'url': 'https://paris.numa.co/Cowork-Accueil',
  'type': 'Co-working space',
  'info': [{'meeting_rooms': 'Yes, Numa Cowork space can be hired for events.',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
{
  'name': 'Cool and Workers',
  'address': '30-34 Rue du Chemin Vert, 75011 Paris',
  'charge': '4 €/hour, 20 €/day'
  'lat': '48.8580496',
  'lon': '2.3733548',
  'url': 'http://www.coolandworkers.com',
  'type': 'Co-working café',
  'info': [{'meeting_rooms': 'Yes',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
{
  'name': "L'Archipel",
  'address': '26 Rue de Saint-Pétersbourg, 75008 Paris',
  'charge': 'Monthly subscription only: from 170 to H330HT €/month',
  'lat': '48.8817333',
  'lon': '2.3256582',
  'url': 'http://www.larchipel.paris/coworking/',
  'type': 'Co-working space',
  'info': [{'meeting_rooms': 'Yes, privatization of space is possible according to your needs.',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
{
  'name': "Café Craft",
  'address': '24 rue des Vinaigriers, 75010 Paris',
  'charge': '3 €/hour',
  'lat': '48.8732358',
  'lon': '2.3630581',
  'url': 'http://cafe-craft.com/home/',
  'type': 'Co-working café',
  'info': [{'meeting_rooms': '?',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
{
  'name': "Draft Atelier",
  'address': '12 Esplanade Nathalie Sarraute, 75018 Paris',
  'charge': 'Co-working: from 8€ up',
  'lat': '48.8879932',
  'lon': '2.3627147',
  'url': 'http://www.ateliers-draft.com',
  'type': 'Co-working space and atelier',
  'info': [{'meeting_rooms': '?',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
{
  'name': 'Le laptop',
  'address': '6 rue Arthur Rozier, 75009 Paris',
  'charge': '25€ / day',
  'lat': '48.877313',
  'lon': '2.3911639',
  'url': 'http://www.lelaptop.com',
  'type': 'Co-working space',
  'info': [{'meeting_rooms': 'Yes, for 4, 6 or fifteen persons.',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
{
  'name': "Les Petites Gouttes",
  'address': '12 Esplanade Nathalie Sarraute, 75018 Paris',
  'charge': "Your meal's worth",
  'lat': '48.8881678',
  'lon': '2.36265',
  'url': 'http://www.lespetitesgouttes.com',
  'type': 'Bistro gourmand with free wi-fi access',
  'info': [{'meeting_rooms': 'no',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
{
  'name': "Coutume Instituutti",
  'address': '60 rue des Écoles ou 33 rue Sommerard, 75005 Paris',
  'charge': "Your coffee's worth",
  'lat': '48.8502448',
  'lon': '2.3433506',
  'url': 'http://coutumecafe.com/s/3231/Coutume+Instituutti',
  'type': 'Café with free wi-fi access',
  'info': [{'meeting_rooms': 'no',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
{
  'name': "Café Coutume",
  'address': '47 Rue de Babylone, 75007, Paris',
  'charge': "Your coffee's worth",
  'lat': '48.8516345',
  'lon': '2.3183272',
  'url': 'http://coutumecafe.com/s/3214/Coutume+Babylone',
  'type': 'Café with free wi-fi access',
  'info': [{'meeting_rooms': 'possibility to reserve the meeting space from Suomi Instituutti',
            'wifi': 'Free Wi-fi'}],
  'photo': ''
},
]